### ISSUE TITLE
Intent Request History no longer available in ASK CLI v2

### ISSUE THREAD

**Issue by btburton42** [alexa/ask-cli#158]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Previously, our organization made use of the `ask api intent-request-history` method as our only window into actual text spoken by customers. This allowed us to get a sense for what our customers were saying; which, in turn, was used to tune sample utterances and provide a better customer experience

## Expected Behavior
There should be a comparable functional method in the v2 CLI.

## Current Behavior
Currently, I am unable to locate a comparable method in the v2 CLI. It is entirely possible that this has been remapped to new functionality, but I don't see it mentioned in documentation or changelog.

## Steps to Reproduce (for bugs)
Pre v2, it was possible to run this command:
`ask smapi intent-requests-history --skill-id SKILL_ID --filters "Name=intent.name, Values=AMAZON.FallbackIntent; Name=stage, Values=Live"` and receive a list of matching user utterances.

## Possible Solution
Please restore this missing functionality or point out something comparable.

## Your Environment and Context
* ask-cli version: 2.3.0

**Comment by kakhaUrigashvili** [comment]
@btburton42 `ask smapi get-utterance-data` should be replacement for 'intent-requests-history'

**Comment by btburton42** [comment]
Thanks. 

Can you provide an example of working syntax to fetch utterance text from a single intent? Passing `ask smapi get-utterance-data --skill-id [SKILL_ID] --intent-name AMAZON.FallbackIntent` still fetches most recent for all intents.

Formerly that was handled by `--filters "Name=intent.name, Values=AMAZON.FallbackIntent; Name=stage, Values=Live"`

Also passing `--stage live` returns no results when I would expect it to only return live.

**Comment by kakhaUrigashvili** [comment]
@btburton42 you found a bug. I created PR to fix it https://github.com/alexa/ask-cli/pull/159

**Comment by kakhaUrigashvili** [comment]
@btburton42 fixed in version 2.4.0

**Comment by btburton42** [comment]
@kakhaUrigashvili thanks for the quick fix! I see that `--stage` flag is still broken. Should I file a separate issue?

**Comment by kakhaUrigashvili** [comment]
@btburton42 can you provide output when you pass --debug flag?
