### ISSUE TITLE
Review of ask-smapi-sdk NPM page needed: typos, incorrect information, wrong repo

### ISSUE THREAD

**Issue by talkingnews** [alexa/ask-cli#264]
at https://www.npmjs.com/package/ask-smapi-sdk there is a "getting started" section.

There's a typo: "clientSecre**c**t"

And the homepage/repo is pointing to https://github.com/alexa/alexa-skill-sdk-for-nodejs and not https://github.com/alexa/ask-cli/

And the quick start doesn't make a lot of sense anyway.

It doesn't explain how to get the vendor id (hint: https://developer.amazon.com/settings/console/mycid)

I assume Client ID, Client Secret is the aws_access_key_id and aws_secret_access_key that I have in .aws/credentials?  (But I have 3 profiles - which one is it using?!)
No matter what I put, I always get this really unhelpful message:

```
Authentication Failed
{"error_description":"Client authentication failed","error":"invalid_client"}
```

I'm struggling with the nightmare that is ask-cliV2. I've managed to build and find some scripts around the web which at least partly rebuild some of the functionality lost in v2, like clone and and an equivelant of "deploy -t lamba".

**All I want to do is just automated the upload of a skill.json and en-GB.json for 20 different skills which have different invocations, but identical voice models and a common lambda code**. It was so easy with v1...

(I thought that an npm page was built from a repo, but I guess not?)

**Comment by kakhaUrigashvili** [comment]
@talkingnews client_id and client_secret is for login with Amazon https://developer.amazon.com/docs/login-with-amazon/minitoc-lwa-overview.html

'ask smapi' provide commands for all methods in ask-smapi-sdk package so you may able to use those commands to automate your tasks.

target flag has been added in the latest release of ask cli.

**Comment by talkingnews** [comment]
Yes, I know client_id and client_secret is for login with Amazon which is why I was using them to make an law token.
But it always gives me this meaningless "invalid client" message.

But I still can't find the command to upload the skill without the lambda? Or even just the voice model?

**Comment by kakhaUrigashvili** [comment]
@talkingnews you should be able to upload skill without lambda using:
`ask deploy --target skill-metadata --ignore-hash`

interaction model can be updated using the following smapi command:
`ask smapi set-interaction-model --skill-id amzn1.ask.skill.9a0c62f4-1022-413e-a398-44a766b05882 --locale en-US --interaction-model file:en-US.json`

**Comment by talkingnews** [comment]
Hi @kakhaUrigashvili - thank you so much. 

OK, it seems I can do what I need with those individual commands.

So I don't need the third one, but I can't seem to get it working anyway.

Do, I download the skill with

ask smapi export-package --stage development --skill-id xxxxxxxx

I get a folder structure with the skill,json and the interaction model, but if I try to push it back up with `ask deploy --target skill-metadata`

I get `[Warn]: Failed to find the ask-resources.json file to deploy with from the current directory.`

But no ask-resources file is downloaded with the package, so I don't know where this comes from. These are existing skills so I'm not using `ask new` here.

(Wow - I really miss `ask clone` and `ask deploy -t <whatever>` - it was all so easy with v1!)

**Comment by kakhaUrigashvili** [comment]
@talkingnews you can create ask-resources.json file by running 'ask init'.

I was able to deploy just skill metadata by running the following steps
1) ask init (provide skill id and other info)
2) ask smapi export-package --stage development --skill-id xxxxxxxx
3) ask deploy --target skill-metadata

seems like `ask init`  suppose to be a replacement for `ask clone`. It does not seems to have all the functionality of `ask clone.` I don't have all the details about this design decision.

**Comment by kakhaUrigashvili** [comment]
@talkingnews looks like typo already has been fixed https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/631
the fix will be reflected with next release to npm. Feel free to contribute and add more info to the readme of ask-smapi-sdk.

**Comment by talkingnews** [comment]
Hi again, I still cannot make this work. At the page 
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/tree/2.0.x/ask-smapi-sdk
it says
"Create a new security profile for your Amazon Developer account by following the instructions provided here"
where "here" is "https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-command-reference.html#generate-lwa-tokens"
But that tells me how to generate an LWA token, not how to create a new login profile.

Then it says at https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/tree/2.0.x/ask-smapi-sdk
"Using the ASK CLI, run: ask util generate-lwa-tokens. You will be asked to provide the Client ID and Client Secret keys from the previous step. This will return the following JSON with a Refresh Token"

But it doesn't - it makes me login via a link (need to use the --no-browser option) and again, I don't get to choose the profile.
